// <auto-generated>
//     Written by Tools/Localization/Generate Keys.
//     Edits are lost on the next run — add the string to the localization source instead.
// </auto-generated>

namespace Game.Runtime
{
	public static class LocalizationKeys
	{
		public static class BetItem
		{
			public const string Colorful = "bet_item.colorful";
			public const string Green = "bet_item.green";
			public const string Purple = "bet_item.purple";
			public const string Red = "bet_item.red";
			public const string Yellow = "bet_item.yellow";
		}

		public static class Common
		{
			public const string Cancel = "common.cancel";
			public const string Close = "common.close";
			public const string Off = "common.off";
			public const string On = "common.on";
		}

		public static class Config
		{
			public const string ItemCapacity = "config.item_capacity";
			public const string ItemsPerHand = "config.items_per_hand";
			public const string LoserBonus = "config.loser_bonus";
			public const string StartingHealth = "config.starting_health";
			public const string Title = "config.title";

			public static class Section
			{
				public const string Items = "config.section.items";
				public const string Match = "config.section.match";
			}
		}

		public static class Hand
		{
			public static class FiveOfAKind
			{
				public const string Description = "hand.five_of_a_kind.description";
				public const string Name = "hand.five_of_a_kind.name";
			}

			public static class Flush
			{
				public const string Description = "hand.flush.description";
				public const string Name = "hand.flush.name";
			}

			public static class FourOfAKind
			{
				public const string Description = "hand.four_of_a_kind.description";
				public const string Name = "hand.four_of_a_kind.name";
			}

			public static class FullHouse
			{
				public const string Description = "hand.full_house.description";
				public const string Name = "hand.full_house.name";
			}

			public static class HighCard
			{
				public const string Description = "hand.high_card.description";
				public const string Name = "hand.high_card.name";
			}

			public static class Pair
			{
				public const string Description = "hand.pair.description";
				public const string Name = "hand.pair.name";
			}

			public static class RoyalFlush
			{
				public const string Description = "hand.royal_flush.description";
				public const string Name = "hand.royal_flush.name";
			}

			public static class Straight
			{
				public const string Description = "hand.straight.description";
				public const string Name = "hand.straight.name";
			}

			public static class StraightFlush
			{
				public const string Description = "hand.straight_flush.description";
				public const string Name = "hand.straight_flush.name";
			}

			public static class ThreeOfAKind
			{
				public const string Description = "hand.three_of_a_kind.description";
				public const string Name = "hand.three_of_a_kind.name";
			}

			public static class TwoPair
			{
				public const string Description = "hand.two_pair.description";
				public const string Name = "hand.two_pair.name";
			}
		}

		public static class Item
		{
			public static class CopyCard
			{
				public const string Copied = "item.copy_card.copied";
				public const string Description = "item.copy_card.description";
				public const string Failed = "item.copy_card.failed";
				public const string Name = "item.copy_card.name";
				public const string Notice = "item.copy_card.notice";
			}

			public static class DeckCount
			{
				public const string Description = "item.deck_count.description";
				public const string Name = "item.deck_count.name";
				public const string Notice = "item.deck_count.notice";
			}

			public static class ExtraDraw
			{
				public const string Description = "item.extra_draw.description";
				public const string Name = "item.extra_draw.name";
				public const string Notice = "item.extra_draw.notice";
			}

			public static class HalfDose
			{
				public const string Description = "item.half_dose.description";
				public const string Name = "item.half_dose.name";
				public const string Notice = "item.half_dose.notice";
				public const string Prompt = "item.half_dose.prompt";
			}

			public static class JokerCard
			{
				public const string Description = "item.joker_card.description";
				public const string Failed = "item.joker_card.failed";
				public const string Joker = "item.joker_card.joker";
				public const string Name = "item.joker_card.name";
			}

			public static class LockFold
			{
				public const string Description = "item.lock_fold.description";
				public const string Name = "item.lock_fold.name";
				public const string Notice = "item.lock_fold.notice";
			}

			public static class MushroomDose
			{
				public const string Description = "item.mushroom_dose.description";
				public const string Doubled = "item.mushroom_dose.doubled";
				public const string Name = "item.mushroom_dose.name";
				public const string Notice = "item.mushroom_dose.notice";
				public const string Nullified = "item.mushroom_dose.nullified";
				public const string Prompt = "item.mushroom_dose.prompt";
			}

			public static class MutualReveal
			{
				public const string Description = "item.mutual_reveal.description";
				public const string Name = "item.mutual_reveal.name";
				public const string Notice = "item.mutual_reveal.notice";
				public const string PromptOwn = "item.mutual_reveal.prompt_own";
				public const string PromptPlayer = "item.mutual_reveal.prompt_player";
				public const string Response = "item.mutual_reveal.response";
			}

			public static class PairLock
			{
				public const string Prompt = "item.pair_lock.prompt";
			}

			public static class PairLockFold
			{
				public const string Description = "item.pair_lock_fold.description";
				public const string Name = "item.pair_lock_fold.name";
				public const string Notice = "item.pair_lock_fold.notice";
			}

			public static class PairLockItems
			{
				public const string Description = "item.pair_lock_items.description";
				public const string Name = "item.pair_lock_items.name";
				public const string Notice = "item.pair_lock_items.notice";
			}

			public static class PeekBoard
			{
				public const string Description = "item.peek_board.description";
				public const string Name = "item.peek_board.name";
				public const string Notice = "item.peek_board.notice";
			}

			public static class PeekBoardMain
			{
				public const string Description = "item.peek_board_main.description";
			}

			public static class PeekHand
			{
				public const string Description = "item.peek_hand.description";
				public const string Name = "item.peek_hand.name";
				public const string Notice = "item.peek_hand.notice";
				public const string Private = "item.peek_hand.private";
			}

			public static class PlaceOnBoard
			{
				public const string Description = "item.place_on_board.description";
				public const string Name = "item.place_on_board.name";
				public const string Notice = "item.place_on_board.notice";
				public const string Prompt = "item.place_on_board.prompt";
			}

			public static class Prompt
			{
				public const string BoardCard = "item.prompt.board_card";
				public const string OpponentCard = "item.prompt.opponent_card";
				public const string OwnCard = "item.prompt.own_card";
				public const string Player = "item.prompt.player";
			}

			public static class RaiseStakes
			{
				public const string Description = "item.raise_stakes.description";
				public const string Name = "item.raise_stakes.name";
				public const string Notice = "item.raise_stakes.notice";
			}

			public static class RandomSuit
			{
				public const string Description = "item.random_suit.description";
				public const string Name = "item.random_suit.name";
				public const string Notice = "item.random_suit.notice";
				public const string Prompt = "item.random_suit.prompt";
			}

			public static class RateShift
			{
				public const string Description = "item.rate_shift.description";
				public const string Lowered = "item.rate_shift.lowered";
				public const string Name = "item.rate_shift.name";
				public const string Prompt = "item.rate_shift.prompt";
				public const string Raised = "item.rate_shift.raised";
			}

			public static class Reason
			{
				public const string AllFaceUp = "item.reason.all_face_up";
				public const string AlreadyCounted = "item.reason.already_counted";
				public const string AlreadyUnder = "item.reason.already_under";
				public const string BoardFaceUp = "item.reason.board_face_up";
				public const string BoardFull = "item.reason.board_full";
				public const string BoardSeen = "item.reason.board_seen";
				public const string CantChange = "item.reason.cant_change";
				public const string CardsFaceUp = "item.reason.cards_face_up";
				public const string DeckEmpty = "item.reason.deck_empty";
				public const string HandFull = "item.reason.hand_full";
				public const string LastBoardSeen = "item.reason.last_board_seen";
				public const string LockedOut = "item.reason.locked_out";
				public const string NoBoard = "item.reason.no_board";
				public const string NoCardToGive = "item.reason.no_card_to_give";
				public const string NoCardToLay = "item.reason.no_card_to_lay";
				public const string NoCountPlace = "item.reason.no_count_place";
				public const string NoStreetLeft = "item.reason.no_street_left";
				public const string NoTime = "item.reason.no_time";
				public const string NobodyInHand = "item.reason.nobody_in_hand";
				public const string NobodyToHalve = "item.reason.nobody_to_halve";
				public const string NobodyToRoll = "item.reason.nobody_to_roll";
				public const string NobodyToShake = "item.reason.nobody_to_shake";
				public const string NobodyToShow = "item.reason.nobody_to_show";
				public const string NobodyToSpike = "item.reason.nobody_to_spike";
				public const string NobodyToSwap = "item.reason.nobody_to_swap";
				public const string NobodyUnseen = "item.reason.nobody_unseen";
				public const string NotDealt = "item.reason.not_dealt";
				public const string NotHeld = "item.reason.not_held";
				public const string NotInHand = "item.reason.not_in_hand";
				public const string OutOfMatch = "item.reason.out_of_match";
				public const string StreetOnly = "item.reason.street_only";
				public const string TurnOnly = "item.reason.turn_only";
				public const string UsedMany = "item.reason.used_many";
				public const string UsedOne = "item.reason.used_one";
				public const string WaitingOther = "item.reason.waiting_other";
			}

			public static class SharedRoll
			{
				public const string Description = "item.shared_roll.description";
				public const string Name = "item.shared_roll.name";
				public const string Notice = "item.shared_roll.notice";
				public const string Prompt = "item.shared_roll.prompt";
			}

			public static class SwapBoard
			{
				public const string Description = "item.swap_board.description";
				public const string Name = "item.swap_board.name";
				public const string Notice = "item.swap_board.notice";
				public const string Prompt = "item.swap_board.prompt";
			}

			public static class SwapHand
			{
				public const string Description = "item.swap_hand.description";
				public const string Name = "item.swap_hand.name";
				public const string Notice = "item.swap_hand.notice";
				public const string PromptOwn = "item.swap_hand.prompt_own";
				public const string PromptPlayer = "item.swap_hand.prompt_player";
				public const string Response = "item.swap_hand.response";
			}

			public static class TableReveal
			{
				public const string Description = "item.table_reveal.description";
				public const string Name = "item.table_reveal.name";
				public const string Notice = "item.table_reveal.notice";
			}
		}

		public static class Loading
		{
			public const string Connecting = "loading.connecting";
			public const string Leaving = "loading.leaving";
			public const string Scene = "loading.scene";
		}

		public static class Lobby
		{
			public const string Empty = "lobby.empty";
			public const string Join = "lobby.join";
			public const string Refresh = "lobby.refresh";
			public const string Searching = "lobby.searching";
			public const string Title = "lobby.title";
		}

		public static class Matchmaking
		{
			public const string Failed = "matchmaking.failed";
			public const string Searching = "matchmaking.searching";
			public const string Title = "matchmaking.title";
			public const string Waiting = "matchmaking.waiting";

			public static class Error
			{
				public const string Connect = "matchmaking.error.connect";
				public const string Create = "matchmaking.error.create";
				public const string Lost = "matchmaking.error.lost";
				public const string Unavailable = "matchmaking.error.unavailable";
			}
		}

		public static class Menu
		{
			public const string Back = "menu.back";
			public const string Credit = "menu.credit";
			public const string Find = "menu.find";
			public const string Host = "menu.host";
			public const string Option = "menu.option";
			public const string Play = "menu.play";
			public const string QuickMatch = "menu.quick_match";
			public const string Quit = "menu.quit";
		}

		public static class Mode
		{
			public const string Main = "mode.main";
		}

		public static class Pause
		{
			public const string Leave = "pause.leave";
			public const string Quit = "pause.quit";
			public const string Resume = "pause.resume";
			public const string Settings = "pause.settings";
			public const string Title = "pause.title";
		}

		public static class Poker
		{
			public const string Pot = "poker.pot";

			public static class Action
			{
				public const string AllIn = "poker.action.all_in";
				public const string Bet = "poker.action.bet";
				public const string Call = "poker.action.call";
				public const string Fold = "poker.action.fold";
			}

			public static class Button
			{
				public const string AddBot = "poker.button.add_bot";
				public const string AllIn = "poker.button.all_in";
				public const string Choose = "poker.button.choose";
				public const string ClearBot = "poker.button.clear_bot";
				public const string Fold = "poker.button.fold";
				public const string Helper = "poker.button.helper";
				public const string Invite = "poker.button.invite";
				public const string Items = "poker.button.items";
				public const string LayBoard = "poker.button.lay_board";
				public const string MatchSettings = "poker.button.match_settings";
				public const string Start = "poker.button.start";
				public const string ViewBoard = "poker.button.view_board";
			}

			public static class Colorful
			{
				public const string Prompt = "poker.colorful.prompt";
			}

			public static class Helper
			{
				public const string Empty = "poker.helper.empty";
				public const string Title = "poker.helper.title";
				public const string YourHand = "poker.helper.your_hand";
			}

			public static class Items
			{
				public const string LeftInDeck = "poker.items.left_in_deck";
			}

			public static class MatchOver
			{
				public const string Nobody = "poker.match_over.nobody";
				public const string Survivor = "poker.match_over.survivor";
			}

			public static class Notice
			{
				public const string ItemBonus = "poker.notice.item_bonus";
				public const string ItemReward = "poker.notice.item_reward";
				public const string ItemUsed = "poker.notice.item_used";
				public const string ItemsLost = "poker.notice.items_lost";
				public const string MatchPlayers = "poker.notice.match_players";
				public const string MatchStarted = "poker.notice.match_started";
			}

			public static class Phase
			{
				public const string AllIn = "poker.phase.all_in";
				public const string Ante = "poker.phase.ante";
				public const string Dealing = "poker.phase.dealing";
				public const string Eating = "poker.phase.eating";
				public const string Finished = "poker.phase.finished";
				public const string FirstStreet = "poker.phase.first_street";
				public const string Looking = "poker.phase.looking";
				public const string MatchOver = "poker.phase.match_over";
				public const string SecondStreet = "poker.phase.second_street";
				public const string Showdown = "poker.phase.showdown";
				public const string Waiting = "poker.phase.waiting";
			}

			public static class Player
			{
				public const string Fallback = "poker.player.fallback";
			}

			public static class Ranking
			{
				public const string Title = "poker.ranking.title";

				public static class Place
				{
					public const string Nd = "poker.ranking.place.nd";
					public const string Rd = "poker.ranking.place.rd";
					public const string St = "poker.ranking.place.st";
					public const string Th = "poker.ranking.place.th";
				}
			}

			public static class Start
			{
				public const string ForTable = "poker.start.for_table";
				public const string Ready = "poker.start.ready";
				public const string Waiting = "poker.start.waiting";
			}

			public static class Targeting
			{
				public const string Hint = "poker.targeting.hint";
			}

			public static class Turn
			{
				public const string Other = "poker.turn.other";
				public const string Yours = "poker.turn.yours";
			}
		}

		public static class Room
		{
			public const string Create = "room.create";
			public const string GameMode = "room.game_mode";
			public const string MaxPlayers = "room.max_players";
			public const string Name = "room.name";
			public const string Private = "room.private";
			public const string Title = "room.title";
		}

		public static class Settings
		{
			public const string AudioSection = "settings.audio_section";
			public const string FpsKey = "settings.fps";
			public const string Graphics = "settings.graphics";
			public const string Language = "settings.language";
			public const string LanguageSection = "settings.language_section";
			public const string Resolution = "settings.resolution";
			public const string Title = "settings.title";
			public const string VoiceSection = "settings.voice_section";
			public const string Vsync = "settings.vsync";
			public const string WindowModeKey = "settings.window_mode";

			public static class Audio
			{
				public const string Background = "settings.audio.background";
				public const string Master = "settings.audio.master";
				public const string Mute = "settings.audio.mute";
				public const string Sfx = "settings.audio.sfx";
			}

			public static class Fps
			{
				public const string Unlimited = "settings.fps.unlimited";
			}

			public static class Voice
			{
				public const string InputVolume = "settings.voice.input_volume";
				public const string MicrophoneKey = "settings.voice.microphone";
				public const string NoiseSuppression = "settings.voice.noise_suppression";
				public const string OutputVolume = "settings.voice.output_volume";
				public const string PlayerVolumes = "settings.voice.player_volumes";
				public const string TalkModeKey = "settings.voice.talk_mode";

				public static class Microphone
				{
					public const string Default = "settings.voice.microphone.default";
				}

				public static class TalkMode
				{
					public const string OpenMic = "settings.voice.talk_mode.open_mic";
					public const string PushToTalk = "settings.voice.talk_mode.push_to_talk";
				}
			}

			public static class WindowMode
			{
				public const string Borderless = "settings.window_mode.borderless";
				public const string Fullscreen = "settings.window_mode.fullscreen";
				public const string Windowed = "settings.window_mode.windowed";
			}
		}
	}
}
