using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Game.Editor.UI
{
	public static class LocalizationKeyGenerator
	{
		private const string OutputPath =
			"Assets/Scripts/Game.Runtime/LocalizationKeys.generated.cs";

		private const string CatalogPath = "Assets/Settings/Localization/LocalizationCatalog.asset";

		[InitializeOnLoadMethod]
		private static void FollowSheetImports()
		{
			Localization.Import.LocalizationImporter.Imported -= HandleStringsImported;
			Localization.Import.LocalizationImporter.Imported += HandleStringsImported;
		}

		private static void HandleStringsImported(Localization.Import.LocalizationImporter _) => Generate();

		private static IEnumerable<string> TableKeys()
		{
			var catalog = AssetDatabase.LoadAssetAtPath<Localization.LocalizationCatalog>(CatalogPath);
			if (!catalog || !catalog.TryGetLocale(catalog.DefaultLocaleCode, out var table)) yield break;

			foreach (var entry in table.Entries) yield return entry.Key;
		}

		[MenuItem("Tools/Localization/Generate Keys")]
		public static void Generate()
		{
			var keys = TableKeys().Distinct().OrderBy(k => k, StringComparer.Ordinal).ToList();

			var root = new Node("LocalizationKeys");
			var skipped = new List<string>();

			foreach (var key in keys)
			{
				if (!TryAdd(root, key)) skipped.Add(key);
			}

			// After every key is in: a clash between a constant and a class depends on keys that
			// may arrive later than the one they collide with.
			ResolveCollisions(root);

			var builder = new StringBuilder();

			builder.AppendLine("// <auto-generated>");
			builder.AppendLine("//     Written by Tools/Localization/Generate Keys.");
			builder.AppendLine("//     Edits are lost on the next run — add the string to the localization source instead.");
			builder.AppendLine("// </auto-generated>");
			builder.AppendLine();
			builder.AppendLine("namespace Game.Runtime");
			builder.AppendLine("{");

			Write(builder, root, 1);

			builder.AppendLine("}");

			var text = builder.ToString();

			// Unchanged keys leave the file alone: rewriting it would recompile every script for nothing.
			if (File.Exists(OutputPath) && File.ReadAllText(OutputPath) == text) return;

			Directory.CreateDirectory(Path.GetDirectoryName(OutputPath) ?? ".");
			File.WriteAllText(OutputPath, text);
			AssetDatabase.ImportAsset(OutputPath);

			if (skipped.Count > 0)
			{
				Debug.LogWarning(
					$"[{nameof(LocalizationKeyGenerator)}] {skipped.Count} key(s) are not valid " +
					$"identifiers and were skipped: {string.Join(", ", skipped)}");
			}

			Debug.Log($"[{nameof(LocalizationKeyGenerator)}] Wrote {keys.Count - skipped.Count} keys to {OutputPath}.");
		}

		private sealed class Node
		{
			public Node(string name) => Name = name;

			public string Name { get; }

			public SortedDictionary<string, Node> Children { get; } = new(StringComparer.Ordinal);

			public SortedDictionary<string, string> Values { get; } = new(StringComparer.Ordinal);
		}

		private static bool TryAdd(Node root, string key)
		{
			var parts = key.Split('.');
			if (parts.Length == 0) return false;

			var node = root;

			// Everything but the last part is a class; the last is the constant.
			for (var i = 0; i < parts.Length - 1; i++)
			{
				var name = ToIdentifier(parts[i]);
				if (name == null) return false;

				if (!node.Children.TryGetValue(name, out var child))
				{
					child = new Node(name);
					node.Children[name] = child;
				}

				node = child;
			}

			var constant = ToIdentifier(parts[^1]);
			if (constant == null) return false;

			node.Values[constant] = key;
			return true;
		}

		private static void ResolveCollisions(Node node)
		{
			var clashing = node.Values.Keys.Where(name => node.Children.ContainsKey(name) || name == node.Name).ToList();

			foreach (var name in clashing)
			{
				var key = node.Values[name];
				node.Values.Remove(name);

				// Suffixed rather than dropped, so both the prefix key and its children stay
				// reachable.
				node.Values[name + "Key"] = key;
			}

			foreach (var child in node.Children.Values) ResolveCollisions(child);
		}

		private static void Write(StringBuilder builder, Node node, int depth)
		{
			var indent = new string('\t', depth);

			builder.AppendLine($"{indent}public static class {node.Name}");
			builder.AppendLine($"{indent}{{");

			foreach (var (name, key) in node.Values)
			{
				builder.AppendLine($"{indent}\tpublic const string {name} = \"{key}\";");
			}

			if (node.Values.Count > 0 && node.Children.Count > 0) builder.AppendLine();

			var first = true;
			foreach (var child in node.Children.Values)
			{
				if (!first) builder.AppendLine();
				first = false;

				Write(builder, child, depth + 1);
			}

			builder.AppendLine($"{indent}}}");
		}

		private static string ToIdentifier(string part)
		{
			if (string.IsNullOrWhiteSpace(part)) return null;

			var builder = new StringBuilder();
			var capitalise = true;

			foreach (var c in part)
			{
				if (c == '_' || c == '-')
				{
					capitalise = true;
					continue;
				}

				if (!char.IsLetterOrDigit(c)) return null;

				builder.Append(capitalise ? char.ToUpperInvariant(c) : c);
				capitalise = false;
			}

			if (builder.Length == 0) return null;

			// An identifier cannot start with a digit.
			if (char.IsDigit(builder[0])) builder.Insert(0, '_');

			return builder.ToString();
		}
	}
}
